@DotNet9Authentication_HostAddress = http://localhost:5086

GET {{DotNet9Authentication_HostAddress}}/weatherforecast/
Accept: application/json,
Authorization: Bearer {token}
###
POST {{DotNet9Authentication_HostAddress}}/login
Content-Type: application/json

{
  "email": "john.alnemeh@gmail.com",
  "password": "Qwe!23",
  "twoFactorCode": "string",
  "twoFactorRecoveryCode": "string"
}
